/********************************************************************
* parts2treeDct.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error parts2treeDct.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableparts2treeDct();
extern void G__cpp_setup_inheritanceparts2treeDct();
extern void G__cpp_setup_typetableparts2treeDct();
extern void G__cpp_setup_memvarparts2treeDct();
extern void G__cpp_setup_globalparts2treeDct();
extern void G__cpp_setup_memfuncparts2treeDct();
extern void G__cpp_setup_funcparts2treeDct();
extern void G__set_cpp_environmentparts2treeDct();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MinimalEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__parts2treeDctLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator;
extern G__linked_taginfo G__parts2treeDctLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__parts2treeDctLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__parts2treeDctLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__parts2treeDctLN_DoubleInBinary;
extern G__linked_taginfo G__parts2treeDctLN_IntInBinary;
extern G__linked_taginfo G__parts2treeDctLN_MinimalEvent;
extern G__linked_taginfo G__parts2treeDctLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__parts2treeDctLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__parts2treeDctLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<double,allocator<double> > G__vectorlEdoublecOallocatorlEdoublegRsPgR;
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
