/********************************************************************
* PrtclDct.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PrtclDct.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePrtclDct();
extern void G__cpp_setup_inheritancePrtclDct();
extern void G__cpp_setup_typetablePrtclDct();
extern void G__cpp_setup_memvarPrtclDct();
extern void G__cpp_setup_globalPrtclDct();
extern void G__cpp_setup_memfuncPrtclDct();
extern void G__cpp_setup_funcPrtclDct();
extern void G__set_cpp_environmentPrtclDct();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PrtclEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PrtclDctLN_TClass;
extern G__linked_taginfo G__PrtclDctLN_TBuffer;
extern G__linked_taginfo G__PrtclDctLN_TMemberInspector;
extern G__linked_taginfo G__PrtclDctLN_TObject;
extern G__linked_taginfo G__PrtclDctLN_ROOT;
extern G__linked_taginfo G__PrtclDctLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PrtclDctLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PrtclDctLN_TClonesArray;
extern G__linked_taginfo G__PrtclDctLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PrtclDctLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PrtclDctLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PrtclDctLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PrtclDctLN_ROOTcLcLMath;
extern G__linked_taginfo G__PrtclDctLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgR;
extern G__linked_taginfo G__PrtclDctLN_PrtclData;
extern G__linked_taginfo G__PrtclDctLN_PrtclEvent;
extern G__linked_taginfo G__PrtclDctLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PrtclDctLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__PrtclDctLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
